AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway for Riot Data Analyzer

Parameters:
  AgentCoreRuntimeArn:
    Type: String
    Default: arn:aws:bedrock-agentcore:us-east-1:661893373836:runtime/riot_data_analyzer-pE01nfE4X0

Resources:
  # Lambda Functions
  CollectSummonerDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: collect-summoner-data
      CodeUri: ../lambda/
      Handler: collect-summoner-data.lambda_handler
      Runtime: python3.13
      Timeout: 60
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref RiotAnalyzerApi
            Path: /summoner/search
            Method: POST

  FetchMatchHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fetch-match-history
      CodeUri: ../lambda/
      Handler: fetch-match-history.lambda_handler
      Runtime: python3.13
      Timeout: 30
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref RiotAnalyzerApi
            Path: /summoner/{riotId}/matches
            Method: GET

  FetchChampionMasteryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fetch-champion-mastery
      CodeUri: ../lambda/
      Handler: fetch-champion-mastery.lambda_handler
      Runtime: python3.13
      Timeout: 30
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref RiotAnalyzerApi
            Path: /summoner/{riotId}/mastery
            Method: GET

  ChampionDataServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: champion-data-service
      CodeUri: ../lambda/
      Handler: champion-data-service.lambda_handler
      Runtime: python3.13
      Timeout: 30
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref RiotAnalyzerApi
            Path: /champions
            Method: GET

  # HTTP API Gateway
  RiotAnalyzerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowOrigins:
          - "*"


Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${RiotAnalyzerApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: RiotAnalyzerApiUrl
  
  ApiId:
    Description: API Gateway ID
    Value: !Ref RiotAnalyzerApi
    Export:
      Name: RiotAnalyzerApiId